# Generated by Django 5.1.6 on 2025-03-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_latitude_attraction_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='location',
        ),
    ]
