# Generated by Django 5.1.6 on 2025-03-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lodging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rating", models.CharField(blank=True, max_length=10)),
                ("link", models.URLField(blank=True)),
                ("price", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("image", models.URLField(blank=True)),
                ("check_in", models.CharField(blank=True, max_length=20)),
                ("check_out", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("completed", "已完成")],
                        default="draft",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
