# Generated by Django 5.1.6 on 2025-03-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lodging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodging",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("completed", "已完成")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
