# Generated by Django 5.1.6 on 2025-03-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lodging", "0002_initial"),
        ("lodging", "0002_lodging_status"),
    ]

    operations = []
