# Generated by Django 5.1.6 on 2025-03-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_alter_lodging_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
