# Generated by Django 5.1.6 on 2025-03-29 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        ('lodging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('completed', '已完成')], default='draft', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDayAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('trip_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.tripday')),
            ],
            options={
                'db_table': 'trips_tripdayattraction',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='tripday',
            name='attractions',
            field=models.ManyToManyField(blank=True, through='trips.TripDayAttraction', to='attractions.attraction'),
        ),
        migrations.CreateModel(
            name='TripLodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_lodgings', to='lodging.lodging')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='trips.trip')),
            ],
        ),
    ]
