# Generated by Django 5.1.6 on 2025-03-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tripdayattraction",
            table="trips_tripday_attractions",
        ),
    ]
