# Generated by Django 5.1.6 on 2025-03-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_tripdayattraction_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tripdayattraction",
            table="trips_tripdayattraction",
        ),
    ]
