# Generated by Django 5.1.6 on 2025-03-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0003_remove_attraction_location"),
        ("trips", "0003_alter_tripdayattraction_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripdayattraction",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attractions.attraction"
            ),
        ),
        migrations.AlterField(
            model_name="tripday",
            name="attractions",
            field=models.ManyToManyField(
                blank=True,
                through="trips.TripDayAttraction",
                to="attractions.attraction",
            ),
        ),
        migrations.DeleteModel(
            name="Attraction",
        ),
    ]
